# Welcome to Jekyll!

# Site settings
title: Website Name

baseurl: "/"
url: "http://yangzhl.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: nickname
  first_name: firstname
  last_name: lastname
  email: your_email@example.com
  facebook_username: facebook_example
  github_username: 'github_example
  head_img: 'path/of/head/img'

# blog img path
img_path: '/path/of/blog/img/'